GET http://localhost:7000/api/books/get-all-books HTTP/1.1
Content-Type: application/json

###
GET http://localhost:7000/api/books/find-book?categories=programming&sortBy=pages HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:7000/homepage HTTP/1.1
Content-Type: application/json

###
POST http://localhost:7000/api/books/add-new-book HTTP/1.1
Content-Type: application/json

{
  "title": "TypeScript funcamentals",
  "author": "Rich Forhmann",
  "pages": 320,
  "categories": [
     "programming", "typescript"
  ],
  "summary": "Learn typescript fundamentals in depth"
}