GET http://localhost:7000/api/books/get-all-books HTTP/1.1
Content-Type: application/json

###
GET http://localhost:7000/api/books/find-book?tags=JavaScript HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:7000/homepage HTTP/1.1
Content-Type: application/json

###
POST http://localhost:7000/api/books/add-new-book HTTP/1.1
Content-Type: application/json

{
  "title": "Getting programming with Nodejs",
  "author": "Jon Drexler",
  "pages": 465,
  "categories": [
    "computer", "programming", "JavaScript"
  ],
  "summary": "Learn Nodejs concepts like a pro"
}